"""Candidate identities for a feature: the real isomers of its formula.

An electron-ionization GC-MS spectrum plus a library hit constrains a feature
to a molecular formula far more tightly than to a single structure, so the
honest candidate set for a feature is the set of compounds sharing its
formula. Those are real compounds from PubChem, not decoys generated by
perturbing the answer, which is what makes the ambiguity in the sections
downstream a measured quantity rather than a modelling choice.

Two properties of this candidate set have to travel with it:

* It is a ceiling, not a working hypothesis. No filter for GC-MS amenability
  (volatility, thermal stability, derivatisability) is applied, so the set
  includes compounds that would never reach the detector. A real workflow
  would consider fewer; nothing here knows how many fewer.
* Above a few hundred isomers the set is sampled, not enumerated. The sample
  is uniform and seeded, so a weighted quantity computed over it is a
  Monte-Carlo estimate of the same quantity over the whole space, with the
  sampling error that implies - and the sampling carries no evidence, so it
  must not be read as a shortlist.

PubChem's formula search is asynchronous: the first response carries a
ListKey, and the CID list appears on a later poll of that key. Property
requests accept a legacy alias for the SMILES column and answer under the
current name: asking for `CanonicalSMILES` returns a `ConnectivitySMILES`
key, so this module asks for `SMILES` and reads `SMILES`.
"""

import json
import random
import time
import urllib.error
import urllib.request

import pandas as pd

PUG = "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound"
MAX_ENUMERATE = 500       # above this the candidate set is sampled
BATCH = 180               # CIDs per property request
_PAUSE = 0.25             # PubChem asks for no more than five requests a second


def _read(url: str, limit: int = 8_000_000, timeout: int = 60,
          attempts: int = 4) -> str:
    """One PUG-REST read, retrying the failures that are not answers.

    Building a study is thousands of sequential requests, so a single gateway
    hiccup would otherwise throw away half an hour of downloads. A 400 or a
    404 is an answer about the query and is raised immediately; a timeout, a
    5xx or a 503 busy reply is retried with a widening pause.
    """
    for k in range(attempts):
        time.sleep(_PAUSE)
        try:
            with urllib.request.urlopen(urllib.request.Request(url),
                                        timeout=timeout) as r:
                return r.read(limit).decode("utf-8", "replace")
        except urllib.error.HTTPError as exc:
            if exc.code < 500 and exc.code != 429:
                raise
            if k == attempts - 1:
                raise
        except (urllib.error.URLError, TimeoutError, OSError):
            if k == attempts - 1:
                raise
        time.sleep(2.0 * (k + 1) ** 2)
    raise RuntimeError("unreachable")


def isomer_cids(formula: str, cache_dir=None, tries: int = 15) -> list:
    """Every PubChem CID with this molecular formula."""
    if cache_dir is not None:
        local = cache_dir / f"cids_{formula}.json"
        if local.exists():
            return json.loads(local.read_text())
    # A formula PubChem will not accept as a query has no candidate set; that is
    # a fact about the feature, not a failure of the notebook, so it returns
    # empty instead of raising into the cell that asked.
    try:
        j = json.loads(_read(f"{PUG}/formula/{formula}/cids/JSON?MaxRecords=100000"))
    except urllib.error.HTTPError as exc:
        if exc.code in (400, 404):
            return []
        raise
    cids = j.get("IdentifierList", {}).get("CID")
    if cids is None:
        key = j["Waiting"]["ListKey"]
        for _ in range(tries):
            time.sleep(2.0)
            try:
                j2 = json.loads(_read(f"{PUG}/listkey/{key}/cids/JSON"))
            except urllib.error.HTTPError as exc:
                if exc.code == 202:      # still running
                    continue
                if exc.code in (400, 404):
                    return []
                raise
            cids = j2.get("IdentifierList", {}).get("CID")
            if cids is not None:
                break
        if cids is None:
            raise TimeoutError(f"PubChem did not finish the formula search for {formula}")
    if cache_dir is not None:
        cache_dir.mkdir(parents=True, exist_ok=True)
        (cache_dir / f"cids_{formula}.json").write_text(json.dumps(cids))
    return cids


def smiles_for(cids, cache_dir=None) -> dict:
    """SMILES per CID, in batches, cached across calls."""
    store, cached = {}, None
    if cache_dir is not None:
        cached = cache_dir / "cid_smiles.json"
        if cached.exists():
            store = json.loads(cached.read_text())
    missing = [c for c in cids if str(c) not in store]
    got = 0
    for i in range(0, len(missing), BATCH):
        chunk = missing[i:i + BATCH]
        ids = ",".join(str(c) for c in chunk)
        try:
            j = json.loads(_read(f"{PUG}/cid/{ids}/property/SMILES/JSON"))
        except (urllib.error.URLError, OSError, ValueError):
            # A batch that survives the retries in _read is left out rather
            # than raised: the candidates in it simply do not get a structure,
            # and the run keeps the ones it already has.
            continue
        for row in j.get("PropertyTable", {}).get("Properties", []):
            if row.get("SMILES"):
                store[str(row["CID"])] = row["SMILES"]
                got += 1
        # Written per batch, so an interrupted build resumes where it stopped
        # instead of re-fetching everything.
        if cached is not None and got:
            cache_dir.mkdir(parents=True, exist_ok=True)
            cached.write_text(json.dumps(store))
    return {int(k): v for k, v in store.items() if int(k) in set(cids)}


def candidate_set(formula: str, n: int = MAX_ENUMERATE, seed: int = 0,
                  cache_dir=None) -> pd.DataFrame:
    """Candidates for one formula, enumerated or uniformly sampled.

    The returned frame carries `n_total` (the size of the whole isomer space)
    and `sampled` on every row, so a caller cannot lose track of whether the
    weights it computes are exact or Monte-Carlo.
    """
    cids = isomer_cids(formula, cache_dir=cache_dir)
    total = len(cids)
    take = cids
    if total > n:
        take = random.Random(seed).sample(cids, n)
    smi = smiles_for(take, cache_dir=cache_dir)
    return pd.DataFrame({"formula": formula,
                         "cid": [c for c in take if c in smi],
                         "smiles": [smi[c] for c in take if c in smi],
                         "n_total": total,
                         "sampled": total > n})


def space_sizes(formulas, cache_dir=None) -> pd.DataFrame:
    """Size of the isomer space per formula - the ambiguity a feature carries."""
    rows = []
    for f in dict.fromkeys(formulas):
        try:
            rows.append({"formula": f, "n_isomers": len(isomer_cids(f, cache_dir=cache_dir))})
        except Exception as exc:
            rows.append({"formula": f, "n_isomers": float("nan"),
                         "note": type(exc).__name__})
    return pd.DataFrame(rows)
